nodeLinker: node-modules

packageExtensions:
  "@jest/core@*":
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true
  eslint-config-next@*:
    peerDependencies:
      next: "*"
  jest-cli@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
  jest@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true
  postcss-loader@*:
    peerDependencies:
      postcss-flexbugs-fixes: "*"
      postcss-preset-env: "*"
      tailwindcss: "*"

yarnPath: .yarn/releases/yarn-3.6.0.cjs

# vercel build uses the node-modules linker and isn't able to find
# dependencies that have been hoisted up.
nmHoistingLimits: "workspaces"
